import { Country } from "./types";

export const countries: Country[] = [
  {
    id: 1,
    code: "NL",
    country: "Netherlands",
    flag: "🇳🇱",
    image: "/assets/esim/netherlands.webp",
    startingPrice: 0,
    packageCount: 0,
    packages: [],
  },
  {
    id: 2,
    code: "PK",
    country: "Pakistan",
    flag: "🇵🇰",
    image: "/assets/esim/pakistan.webp",
    startingPrice: 0,
    packageCount: 0,
    packages: [],
  },
  {
    id: 3,
    code: "AE",
    country: "United Arab Emirates",
    flag: "🇦🇪",
    image: "/assets/esim/uae.webp",
    startingPrice: 0,
    packageCount: 0,
    packages: [],
  },
  {
    id: 4,
    code: "SA",
    country: "Saudi Arabia",
    flag: "🇸🇦",
    image: "/assets/esim/saudi.webp",
    startingPrice: 0,
    packageCount: 0,
    packages: [],
  },
  {
    id: 5,
    code: "TR",
    country: "Turkey",
    flag: "🇹🇷",
    image: "/assets/esim/turkey.webp",
    startingPrice: 0,
    packageCount: 0,
    packages: [],
  },
  {
    id: 6,
    code: "IN",
    country: "India",
    flag: "🇮🇳",
    image: "/assets/esim/india.webp",
    startingPrice: 0,
    packageCount: 0,
    packages: [],
  },
];
